# Generated by Django 4.2.28 on 2026-02-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigo',
            options={'ordering': ['-movido_em']},
        ),
        migrations.AddField(
            model_name='artigo',
            name='movido_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
