# Generated by Django 4.2.28 on 2026-02-15 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0002_alter_artigo_options_artigo_movido_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_proprias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('nome', 'dono')},
            },
        ),
        migrations.AddField(
            model_name='artigo',
            name='lista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='compras.lista'),
        ),
        migrations.CreateModel(
            name='ListaPartilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partilhas', to='compras.lista')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_partilhadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('lista', 'utilizador')},
            },
        ),
    ]
